import 'package:flutter/material.dart';
import 'package:just_chicken/models/product.dart';
import 'package:just_chicken/widgets/product_item.dart';

class BuffalowingScreen extends StatefulWidget {
  const BuffalowingScreen({ Key? key }) : super(key: key);
  static const routeName = "/Buffalowing-Screen";

  @override
  _BuffalowingScreenState createState() => _BuffalowingScreenState();
}

class _BuffalowingScreenState extends State<BuffalowingScreen> {
   final List<Product> loadedProducts = [
    Product(
        id: "p1",
        title: "Blondies",
        ingredients: 'Blondies are often called brownies without chocolate because it\'s all  about brown sugar. Blondies are a dessert with their own unique deliciousness and personality.',
       description: [
          "1/2 cup (1 stick, 112 g) butter, melted",
          "1 cup (220 g) tightly packed dark brown sugar",
          "1 large egg, lightly beaten",
          "1 teaspoon of vanilla",
          "1/2 teaspoon baking powder",
          "1/8 teaspoon baking soda",
          "Pinch of salt",
          "1 cup (128 g) all-purpose flour",
          "1/3 cup (60 g) butterscotch chips (chopped walnuts and chocolate chips are equally tasty)",
        ],
        price: 21.47,
    imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/blondies1-1.jpg'),
    Product(
        id: "p2",
        title: "Carrot Cake",
        ingredients:  'Carrot cake is cake that contains carrots mixed into the batter. Most modern carrot cake recipes have a white cream cheese frosting. Sometimes pecans, pineapple, and shredded coconut is added in the mix.', //Your Description Here,
        description: [
          "6 cups grated carrots",
          "1 cup brown sugar",
          "1 cup raisins",
          "4 large eggs eggs",
          "1 ½ cups white sugar",
          "1 cup vegetable oil",
          "2 teaspoons vanilla",
          "1 cup crushed pineapple, drained",
          "3 cups all-purpose flour",
          "1 ½ teaspoons baking soda",
          "1 teaspoon salt",
          "4 teaspoons ground cinnamon",
          "1 cup chopped walnut",
        ],
        price: 24.09,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/carrot-cake-1.jpg',),
    Product(
        id: "p3",
        title: "Chocolate Cake",
        ingredients:  'Chocolate cake or chocolate gâteau is a cake flavored with melted chocolate, cocoa powder, or both',
        description: [
          "1 (18.25 ounce) package devil's food cake mix",
          "1 (5.9 ounce) package instant chocolate pudding mix",
          "1 cup sour cream",
          "1 cup vegetable oil",
          "4 large eggs eggs",
          "½ cup warm water",
          "Pinch of salt",
          "2 cups semisweet chocolate chips",
        ],
        price: 19.89,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/chocolate-cake-1.jpg'),
    Product(
        id: "p4",
        title: "Strawberry Cake",
        ingredients: 'This vibrant pink layer cake is pure strawberry-on-strawberry goodness, with fresh strawberries going into the cake batter and frosting',
       description: [
          "1 (18.25 ounce) package yellow cake mix",
          "1 (3 ounce) package strawberry flavored Jell-O® mix",
          "3 tablespoons all-purpose flour",
          "½ cup water",
          "⅔ cup vegetable oil",
          "4 large eggs eggs",
          "1 (10 ounce) package frozen strawberries",
          "½ cup butter",
          "4 ¾ cups confectioners' sugar",
        ],
        price: 29.99,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/Strawberrycake-_and-frosting-1.jpg'),
    Product(
        id: "p5",
        title: "Coconut Cake",
        ingredients: 'Coconut cake is a popular dessert in the Southern region of the United States. It is a cake frosted with a white frosting and covered in coconut flakes.',
        description: [
          "3/4 pound (3 sticks) unsalted butter, at room temperature, plus more for greasing the pans",
          "2 cups sugar",
          "5 extra-large eggs, at room temperature",
          "1 1/2 teaspoons pure vanilla extract",
          "1 1/2 teaspoons pure almond extract",
          "3 cups all-purpose flour, plus more for dusting the pans",
          "1 teaspoon baking powder",
          "1/2 teaspoon baking soda",
          "1/2 teaspoon kosher salt",
          "1 cup milk",
          "4 ounces sweetened shredded coconut",
          "For the frosting:",
          "1 pound cream cheese, at room temperature",
          "1/2 pound (2 sticks) unsalted butter, at room temperature",
          "3/4 teaspoon pure vanilla extract",
          "1/4 teaspoon pure almond extract",
          "1 pound confectioners' sugar, sifted",
          "6 ounces sweetened shredded coconut",
        ],
        price: 31.89,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/coconut-cake-1.jpg'),
    Product(
        id: "p6",
        title: "Red Velvet",
        ingredients:   'Red velvet is such a unique cake because it has a vanilla flavor but also a hint of chocolate. It can also be hard to get just right because it should be buttery, yet stay moist. This recipe delivers all of that and it’s incredibly delicious too!',
        description: [
          "2 and 2/3 cups (295 grams) cake flour (spooned & leveled)",
          "1/4 cup (22 grams) natural unsweetened cocoa powder",
          "1 teaspoon baking soda",
          "1/2 teaspoon salt",
          "1/2 cup (115 grams) unsalted butter softened to room temperature",
          "1 and 3/4 cups (350 grams) granulated sugar",
          "2 large eggs room temperature",
          "1/2 cup (120 ml) canola or vegetable oil",
          "1 (1-ounce) bottle liquid red food color",
          "2 teaspoons pure vanilla extract",
          "1 teaspoon distilled white vinegar",
          "1 and 1/3 cups (320 ml) buttermilk room temperature",
          "for_the_frosting :",
          "12 ounces cream cheese softened",
          "3/4 cup (175 grams) unsalted butter softened to room temperature",
          "3 cups (360 grams) powdered sugar",
          "1 and 1/2 teaspoons pure vanilla extract",
        ],
        price: 23.9,
        imageUrl:  'https://flutterfix.com/wp-content/uploads/2020/08/Red-velvet-1.jpg'),
    Product(
        id: "p7",
        title: "Whole Wheat",
        ingredients: 'These pancakes are made with whole wheat flour and naturally sweetened with honey but they’re still incredibly soft and light.',
        description: [
       "2 cups (240 grams) white whole wheat flour or whole wheat flour (spooned & leveled)",
          "2 teaspoons baking powder",
          "1 teaspoon baking soda",
          "1/2 teaspoon salt",
          "1 and 3/4 cup (420 ml) buttermilk (I used low-fat)",
          "1/4 cup (85 grams) honey",
          "3 tablespoons (45 ml) oil (canola, vegetable, or melted coconut oil)",
          "2 large eggs",
          "2 teaspoons pure vanilla extract",
    ],
        price: 19.69,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/whole-wheat-pancakes-1.jpg'),
    Product(
        id: "p8",
        title: "Buttermilk",
        ingredients: 'These light and fluffy buttermilk pancakes are so easy to make and turn out perfect every single time. Perfect for breakfast, brunch, or even dinner!',
        description: [
        "2 cups (250 grams) all-purpose flour (spooned & leveled)",
          "2 teaspoons baking powder",
          "1 teaspoon baking soda",
          "1/2 teaspoon salt",
          "1 and 3/4 cup (420 ml) buttermilk",
          "3 tablespoons (40 grams) granulated sugar",
          "3 tablespoons (45 ml) oil (canola, vegetable, or melted coconut oil)",
          "2 large eggs",
          "2 teaspoons pure vanilla extract",
    ],
        price: 29.00,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/buttermilk-pancakes-1.jpg'),
    Product(
        id: "p9",
        title: "Cranberry",
        ingredients: 'This Sparkling Cranberry White Chocolate Cake recipe is a new Christmas fav! The cake is incredibly moist & flavorful with colorful sparkling cranberries.',
        description: [
    "2 cups fresh cranberries",
          "1 1/2 cups (310g) sugar, divided",
          "1 cup (240ml) water",
          "CRANBERRY CAKE:",
          "3 1/3 cups (433g) all purpose flour",
          "2 cups (414g) sugar",
          "2 1/2 tsp baking powder",
          "1 1/2 cups (336g) salted butter (340g), room temperature",
          "3 eggs",
          "2 tbsp vanilla extract",
          "1 cup (240ml) sour cream",
          "1 cup (240ml) milk",
          "3 cups fresh cranberries",
          "WHITE CHOCOLATE ICING :",
          "12 oz white chocolate chips",
          "3/4 cup (180ml) heavy whipping cream",
          "3/4 cup (168g) butter, room temperatur",
          "8–9 cups (920-1035g) powdered sugar",
    ],
        price: 15.89,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/Cranberry-Cheesecake-Cake-3-1.jpg'),
    Product(
        id: "p10",
        title: "Banana Cake",
        ingredients: 'This is a very versatile and fast cake recipe. Not only is it moist and delicious, the same batter can be used to make banana bread and muffins. Delicious frosted with chocolate or cream cheese frosting.',
        description: [
    "2 ½ cups all-purpose flour",
          "1 pinch salt",
          "1 teaspoon baking soda",
          "½ cup unsalted butter",
          "1 cup white sugar",
          "¾ cup light brown sugar",
          "4 medium (7 inches to 7-7/8 inches long)s ripe bananas, mashed",
          "2 large eggs",
          "⅔ cup buttermilk",
          "½ cup chopped walnuts",
    ],
        price: 25.82,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/bananacake.jpg'),
    Product(
        id: "p11",
        title: "Caramel Banana",
        ingredients: 'Moist banana cake layers covered in caramel sauce & frosted with more caramel frosting! This awesome Caramel Banana Layer cake is a must try banana dessert.',
        description: [
     "1 1/2 cups (310g) sugar",
          "3/4 cup (168g) unsalted butter, room temperature",
          "1/2 tsp vanilla extract",
          "3/4 cup (173g) sour cream",
          "3 tbsp (45ml) vegetable oil",
          "3 large eggs",
          "1 large egg white",
          "2 1/2 cups (325g) all purpose flour",
          "2 tsp baking powder",
          "1/2 tsp baking soda",
          "1/2 tsp salt",
          "1 cup (240ml) mashed bananas (2–3 medium sized bananas)",
          "Additional : Banana chips, Caramel Sauce",
          "For the Caramel Frosting:",
          '1 1/2 cups (336g) salted butter,',
          '1 1/4 cups (237g) shortening',
          '10 1/2 cups (1208g) powdered sugar',
          '2 tsp vanilla extract',
          '7 tbsp caramel sauce (above) room temperature',
          '3 tbsp water',
    ],
        price: 22.95,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/banana-caramel-layer-1.jpg'),
    Product(
        id: "p12",
        title: "Lemon Blueberry",
        ingredients: 'This easy Lemon Blueberry Layer Cake is bursting with fresh blueberries and lemon flavor. Topped with homemade cream cheese frosting, this classic cake recipe is perfect for summer!',
        description: [
     "2 3/4 cups + 2 tbsp (374g) all-purpose flour",
          "1 3/4 tsp baking powder",
          "1/4 tsp baking soda",
          "1/2 tsp salt",
          "1/2 cup (112g) unsalted butter, room temperature",
          "1/2 cup (120ml) vegetable oil",
          "1 3/4 cups (362g) sugar",
          "1 tsp vanilla extract",
          "6 tbsp (86g) sour cream",
          "4 large eggs",
          "1/2 cup (120ml) fresh lemon juice",
          "2 tbsp fresh lemon zest (about 3 large lemons)",
          "1/4 cup (60ml) buttermilk",
          "1 3/4 cups (about 260g) blueberries",
          "CREAM CHEESE FROSTING :",
          "16 oz (452g) cream cheese, room temperature",
          "1 cup (224g) butter, room temperature",
          "11 cups (1265g) powdered sugar",
          "2 tsp vanilla extract",
          "Lemon slices",
          "Blueberries, for decorating",
    ],
    price: 32.80,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/lemon-blueberry-1.jpg'),
    Product(
        id: "p13",
        title: "Strawberry Crunch",
        ingredients:  'This Strawberry Crunch Ice Cream Cake is made with strawberry and vanilla ice cream, plus strawberry shortcake crunchies! It’s a delicious cake that’s perfect for summer!',
        description: [
     "STRAWBERRY CRUNCHIES:",
          "1 cup (130g) all purpose flour, divided",
          "1/2 cup (155g) sugar, divided",
          "3/4 cup freeze dried strawberries",
          "7 tbsp salted butter, room temperature, divided",
          "1/2 tsp vanilla extract",
          "ICE CREAM LAYERS :",
          "1.5 quart container strawberry ice cream",
          "1.5 quart container vanilla ice cream",
          "WHIPPED CREAM:",
          "1 3/4 cups (420ml) heavy whipping cream, cold",
          "3/4 cup (86g) powdered sugar",
          "1 1/4 tsp vanilla extract",
          "1/2 cup freeze dried strawberries",
          "Red and Ivory gel icing color, optional",
    ],
        price: 9.89,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/strawberry-crunch-icecream-1.jpg'),
    Product(
        id: "p14",
        title: "Red Velvet",
        ingredients: 'This Red Velvet Cheesecake Cake recipe has layers of moist red velvet cake and creamy cheesecake, covered in cream cheese frosting! If you’ve ever had the cheesecake and loved it, this is the perfect recipe to make at home!',
        description: [
     "VANILLA CHEESECAKE:",
          "24 oz (678g) cream cheese, room temperature",
          "1 cup (207g) sugar",
          "3 tbsp (24g) all purpose flour",
          "1 cup (230g) sour cream",
          "1 tbsp vanilla extract",
          "4 large eggs, room temperature",
          "RED VELVET CAKE LAYERS :",
          "2 1/2 cups (325g) all purpose flour",
          "2 cups (414g) sugar",
          "1 1/4 tsp baking soda",
          "1/2 tsp baking powder",
          "4 tsp (9g) natural unsweetened cocoa",
          "1 tsp salt",
          "1 cup (240ml) buttermilk",
          "1/2 cup (120ml) vegetable oil",
          "2 tsp vanilla extract",
          "2 large eggs",
          "2 tsp white vinegar",
          "4 tsp red food coloring",
          "1 cup (240ml) hot water",
          "CREAM CHEESE FROSTING :",
          "16 oz (452g) cream cheese, room temperature",
          "1 1/4 cups (280g) butter, room temperature",
          "12 cups (1380g) powdered sugar",
          "2 tsp vanilla extract",
          "6 oz white chocolate chips",
          "RED GANACHE :",
          "6 oz red Wilton candy melts",
          "3 tbsp heavy whipping cream",
          "Sprinkles",
    ],
        price: 21.09,
        imageUrl: 'https://flutterfix.com/wp-content/uploads/2020/08/red-velvet-cheesecake-1.jpg'),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.amber,
        title: const Text("Cakes"),
      ),
      body:  Column(
        children: [
          Flexible(
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(20),
                      child: GridView.builder(
                        padding: const EdgeInsets.all(10),
                        itemCount: loadedProducts.length,
                        itemBuilder: (ctx, i) => ProductItem(
                          loadedProducts[i].id,
                          loadedProducts[i].title,
                          loadedProducts[i].imageUrl,
                          loadedProducts[i].price,
                          loadedProducts[i].description,
                          loadedProducts[i].ingredients,
                        ),
                        gridDelegate:
                            const SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: 2,
                          childAspectRatio: 3 / 2,
                          crossAxisSpacing: 10,
                          mainAxisSpacing: 10,
                        ),
                      ),
                    ),
                  
                ),
        ],
      ));
  }
}